export { default as Test } from './test/Test'
export { default as Home } from './home/Home'
export { default as SignIn } from './signin/SignIn'
export { default as SignUp } from './signup/SignUp'
export { default as Product } from './product/Product'
export { default as UpdateProduct } from './updateproduct/UpdateProduct'
export { default as Cart } from './cart/Cart'