export { default as Home } from './home/Home'
export { default as Cart } from './cart/Cart'
export { default as Product } from './product/Product'
export { default as LogIn } from './login/LogIn'
export { default as SignUp } from './signup/SignUp'
export { default as Forum } from './Forum/Forum'